#!/bin/bash
mv /System/Library/PreferenceBundles/ScheduleSettings.bundle /System/Library/PreferenceBundles/tmp/Sched.bak
mv /System/Library/PreferenceBundles/AccountSettingsUI.bundle/en.lproj /System/Library/PreferenceBundles/tmp/Acct.bak
mv /System/Library/PreferenceBundles/tmp/Sched /System/Library/PreferenceBundles/ScheduleSettings.bundle
mv /System/Library/PreferenceBundles/tmp/Acct /System/Library/PreferenceBundles/AccountSettingsUI.bundle/en.lproj

cat - <<EOS
------------------------------------------
        Installing PushMod64
------------------------------------------

Thanks for using PushMod64! -iSteve-O

Twitter: @iSteve_O

Installing New Push Settings...

Complete. Enjoy!

EOS
